name: Build Release

on:
  push:
    branches: main
  pull_request:
     branches: [ main ]
     
env:
   # Solution file name
   SOLUTION_FILE_PATH: DemoApp.sln

jobs:
  build:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v2
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Navigate to Workspace
      run: cd $GITHUB_WORKSPACE

    - name: Create Build Directory
      run: mkdir _build
      
    - name: Restore Packages
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}

    - name: Build Solution
      run: |
        msbuild.exe ${{env.SOLUTION_FILE_PATH}} /property:Configuration=Release /p:OutputPath=../_build -p:VisualStudioVersion=15.0
        
    
